CREATE SCHEMA IF NOT EXISTS ecommerce;

CREATE TABLE IF NOT EXISTS ecommerce.app_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ecommerce.product (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    price DOUBLE PRECISION,
    description VARCHAR(255),
    stock INTEGER,
    category VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ecommerce.cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES ecommerce.app_user (user_id),
    product_id BIGINT REFERENCES ecommerce.product (product_id),
    quantity INTEGER,
    status VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ecommerce.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES ecommerce.app_user (user_id),
    total_price DOUBLE PRECISION,
    order_date TIMESTAMP(6),
    status VARCHAR(255)
);