spring.application.name=EcommerceBackend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ecommerce_backend}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}

server.port=8000

spring.jpa.properties.hibernate.default_schema=ecommerce
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true